#Lab4_AssignedWork
rm(list=ls())
setwd("C:\\Users\\Rituraj Anand\\Desktop\\Sem6\\CSE3506\\LAB\\Lab 4")
credit=read.csv("CreditWorthiness.csv")
str(credit)
credit$credit.status <- as.factor(credit$credit.status)
credit$education <- as.factor(credit$education)
credit$m.status <- as.factor(credit$m.status)
credit$Oparties <- as.factor(credit$Oparties)
credit$Duration <- as.factor(credit$Duration)
credit$inPlans <- as.factor(credit$inPlans)
credit$JobType <- as.factor(credit$JobType)
credit$Ndepend <- as.factor(credit$Ndepend)
credit$telephone <- as.factor(credit$telephone)
credit$foreign <- as.factor(credit$foreign)
credit$creditScore <- as.factor(credit$creditScore)
str(credit)
set.seed(325)
credit2 <- sample(2, nrow(credit), replace=T, prob = c(0.71, 0.29))
train <- credit[credit2==1,]
tst <- credit[credit2==2,]
model <- glm(creditScore~credit.status+Loan.required+education+m.status+Oparties+Duration+age+inPlans+JobType+Ndepend+telephone+foreign, data=train, family='binomial')
summary(model)
model <- glm(creditScore~credit.status+Loan.required+education+foreign, data=train, family='binomial')
summary(model)
pre <- predict(model, train, type='response')
head(pre)
head(train)

